### ISSUE TITLE
Problem starting node

### ISSUE THREAD

**Issue by jrm93** [ggauravr/slack-sample-cli#3]
Hi,

Whenever i start the node the app crashes with following error trace.

```
info: RTM client authenticated.
error:  TypeError: slackTerminal.getCommandObjects is not a function
    at Object.<anonymous> (/Users/junior/Desktop/Development/slack-sample-cli/commands/help.js:2:29)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at /Users/junior/Desktop/Development/slack-sample-cli/node_modules/slack-terminalize/dispatcher.js:47:23
    at Array.forEach (native)
    at Object.init (/Users/junior/Desktop/Development/slack-sample-cli/node_modules/slack-terminalize/dispatcher.js:46:24)
    at _listen (/Users/junior/Desktop/Development/slack-sample-cli/node_modules/slack-terminalize/index.js:21:13)
    at RTMClient.<anonymous> (/Users/junior/Desktop/Development/slack-sample-cli/node_modules/slack-terminalize/index.js:40:4)
    at RTMClient.emit (/Users/junior/Desktop/Development/slack-sample-cli/node_modules/eventemitter3/index.js:116:35)
    at RTMClient.emit (/Users/junior/Desktop/Development/slack-sample-cli/node_modules/@slack/client/lib/clients/client.js:86:39)
    at RTMClient._onStart (/Users/junior/Desktop/Development/slack-sample-cli/node_modules/@slack/client/lib/clients/rtm/client.js:273:10)
```

**Comment by eskimoblood** [comment]
Its fixed in [this pull request](https://github.com/ggauravr/slack-sample-cli/pull/2/files)

**Comment by ggauravr** [comment]
Thanks guys. I merged the PR for the fix to this.

**Comment by ggauravr** [comment]
@JRM93 Can you please confirm if it fixes your issue, and I can close this issue. Thanks!
